# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yBSk1AuRkpYaMLjAPoLwrFF3j8GhkWUP
"""

# ==============================================================================
# SECTION 1: DEPENDENCY INSTALLATION & IMPORTS
# ==============================================================================
!pip install ucimlrepo

import os
import zipfile
import joblib
import pandas as pd
import numpy as np
from pathlib import Path
from google.colab import files as colab_files
from ucimlrepo import fetch_ucirepo

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score, roc_auc_score, precision_score,
    recall_score, f1_score, matthews_corrcoef
)

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier

# ==============================================================================
# SECTION 2: ENVIRONMENT & DIRECTORY SETUP
# ==============================================================================
MODEL_DIR = Path("model")
MODEL_DIR.mkdir(exist_ok=True)

print("Created 'model/' directory for serialized artifacts.")

# ==============================================================================
# SECTION 3: DATA FETCHING & PREPROCESSING (Spambase - UCI ID 94)
# ==============================================================================
print("\nFetching Spambase dataset from UCI Repository (ID: 94)...")
spambase = fetch_ucirepo(id=94)

X = spambase.data.features.copy()
y = spambase.data.targets.iloc[:, 0].copy()

# Handle missing values if any
X = X.fillna(X.median())

# Train-Test Split (80% Train, 20% Test -> 921 test instances)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Fit StandardScaler on training features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Export Scaler binary
joblib.dump(scaler, MODEL_DIR / "scaler.joblib")
print("Saved 'scaler.joblib' to 'model/' directory.")

# ==============================================================================
# SECTION 4: MODEL TRAINING & METRICS EVALUATION
# ==============================================================================
models = {
    "logistic_regression.joblib": LogisticRegression(max_iter=1000, random_state=42),
    "decision_tree.joblib": DecisionTreeClassifier(max_depth=5, random_state=42),
    "knn.joblib": KNeighborsClassifier(n_neighbors=5),
    "naive_bayes.joblib": GaussianNB(),
    "random_forest.joblib": RandomForestClassifier(n_estimators=100, max_depth=5, random_state=42)
}

print("\n" + "="*50)
print("           MODEL PERFORMANCE METRICS           ")
print("="*50)

results = []

for filename, model in models.items():
    model_name = filename.replace('.joblib', '').replace('_', ' ').title()

    # Scale inputs for distance/gradient-based models
    if "logistic" in filename or "knn" in filename or "naive" in filename:
        model.fit(X_train_scaled, y_train)
        y_pred = model.predict(X_test_scaled)
        y_prob = model.predict_proba(X_test_scaled)[:, 1]
    else:
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        y_prob = model.predict_proba(X_test)[:, 1]

    # Compute evaluation metrics
    acc = accuracy_score(y_test, y_pred)
    auc = roc_auc_score(y_test, y_prob)
    prec = precision_score(y_test, y_pred, zero_division=0)
    rec = recall_score(y_test, y_pred, zero_division=0)
    f1 = f1_score(y_test, y_pred, zero_division=0)
    mcc = matthews_corrcoef(y_test, y_pred)

    results.append({
        'Model Name': model_name,
        'Accuracy': round(acc, 4),
        'AUC': round(auc, 4),
        'Precision': round(prec, 4),
        'Recall': round(rec, 4),
        'F1': round(f1, 4),
        'MCC': round(mcc, 4)
    })

    # Export binary
    joblib.dump(model, MODEL_DIR / filename)

# Print metrics summary table
metrics_df = pd.DataFrame(results)
print(metrics_df.to_string(index=False))

# ==============================================================================
# SECTION 5: EXPORT TEST DATASET & PACKAGE FOR DOWNLOAD
# ==============================================================================
test_df = X_test.copy()
test_df['target'] = y_test.values
test_df.to_csv("test_data.csv", index=False)
print("\nExported 'test_data.csv' to root directory.")

zip_filename = "ml_assignment_artifacts.zip"
with zipfile.ZipFile(zip_filename, 'w', zipfile.ZIP_DEFLATED) as zipf:
    zipf.write("test_data.csv")
    for root, _, filenames in os.walk(MODEL_DIR):
        for file in filenames:
            file_path = os.path.join(root, file)
            zipf.write(file_path, os.path.relpath(file_path, "."))

print(f"\nSuccessfully archived artifacts into '{zip_filename}'. Starting automatic download...")

colab_files.download(zip_filename)